### ISSUE TITLE
running convox fails with: Exec format error

### ISSUE THREAD

**Issue by oren** [convox/cli#36]
sudo -i
curl -Ls http://www.convox.com/downloads/osx/convox.zip > /tmp/convox.zip
unzip /tmp/convox.zip -d /usr/local/bin
convox

```
bash: /usr/local/bin/convox: cannot execute binary file: Exec format error
```

I am on Ubuntu 15.04

**Comment by ddollar** [comment]
I added Linux instructions here: https://docs.convox.com/

Let me know if whether or not you already have `unzip` installed on your system.

**Comment by oren** [comment]
work now. thank you.

**Comment by thejohnha** [comment]
I seem to have this exact same issue. Tried on Ubuntu 16.04 and 17.04 and 17.10. Worked for me last week, but not this week. Hmmm.... Could the issue be between my ears? Any help would be appreciated... Thank you.
