### ISSUE TITLE
attempt to deploy the sinatra example shows ERROR: no such app: sinatra

### ISSUE THREAD

**Issue by oren** [convox/cli#39]
I follow the docs for deploying the sinatra example app:

```
convox apps
```
APP  STATUS

```
git clone git@github.com:convox-examples/sinatra.git
cd sinatra
convox deploy
```
ERROR: no such app: sinatra

**Comment by ddollar** [comment]
This recently changed. I'll fix the docs. You will need to create the app first:

    $ convox apps create sinatra

**Comment by oren** [comment]
```
convox apps create
```
Creating app sinatra:

Is the user expected to type a name for the app? if that's the case maybe it should say:
```
Creating app. name: (sinatra)
```

**Comment by ddollar** [comment]
The app name is optional. If you don't specify it, the current directory name will be used.

**Comment by oren** [comment]
Thanks! I figure it out, but i think it would be nice to be more explicit about it. I wasn't sure what to do so I just hit 'enter'. waited a minute and than typed 'convox apps' to find it.

**Comment by ddollar** [comment]
Good suggestion, we'll look into making it more explicit
