### ISSUE TITLE
Is it possible to set convox to always use dedicated instances?

### ISSUE THREAD

**Issue by oren** [convox/cli#40]
my ec2 instances should be on dedicated instaces. is it possible to configure convox to only use those? if not, I will be happy to send a PR.

**Comment by ddollar** [comment]
It's not currently possible but you could modify the main CloudFormation script here:
https://github.com/convox/kernel/blob/master/dist/kernel.json

Would probably be good to make that a boolean parameter.

**Comment by oren** [comment]
great! it will be nice to have a 'developers' section in the website with instructions for newbies that want to contribute to the code base. stuff like what repos to clone (or fork), how to run it locally and where to find stuff. I would like to be the guinea pig for this section, if you think it's a good idea to have it.

**Comment by ddollar** [comment]
Yes, I think it's a good idea. We have the start of such a document here:
https://github.com/convox/kernel/blob/master/README.md

**Comment by oren** [comment]
thanks. i guess the question how will someone new to this project know to go there? maybe i link from the website would help?

I am going to follow the README (while ignoring boot2docker since I am on ubuntu with docker already installed). I already have the cli installed on this laptop. will following the instructions destroy my current cli? is there a way to keep my current (official cli) while contributing to the project?

**Comment by ddollar** [comment]
You should be able to ignore the CLI directions since you already have one. If you end up working on the CLI you may need to keep a local dev version but that won't be necessary for now.

**Comment by oren** [comment]
the first line is
```
mkdir -p ~/.convox ; echo dev@convox.com > ~/.convox/id
```

I am not sure if I want to run it since I already have content in this file. will it cause any issues if i override the content with dev@convox.com ? btw, i am still in the process of deploying the sinatra app and it say: 'waiting for app...' it's more than 10 minutes since i run the deploy command.

Also, if you think some of my questions don't belong to this issue i can create another issue or we can chat in IRC (#convox on freenode).

**Comment by ddollar** [comment]
@oren solved this in #41
