### ISSUE TITLE
Failing tests on tip due to golang error message change

### ISSUE THREAD

**Issue by josegonzalez** [convox/cli#53]
Seems [this commit](https://github.com/golang/go/commit/0fc582e87942b2e52bed751b6c56660ba99e9a7d#diff-ae34eb42831ffecf011ea43c6429582cR456) in Golang 1.5 broke the [`login_test`](https://github.com/convox/cli/blob/master/convox/login_test.go#L54) when a bad host is used.

I tried fixing this but it looks like the `expect` test compares marshalled json bytes for error output, and not the actual messages. Not sure what the best way to fix the issue would be, but thought I'd document it so that others might be saved from spelunking in the golang core.

**Comment by nzoschke** [comment]
Thanks for the report. Yeah, we will need to improve the `expect` logic to make a regex or similar easier to use.

**Comment by nzoschke** [comment]
https://github.com/stretchr/testify looks like a good library to improve testing

**Comment by nzoschke** [comment]
I disabled testing on tip right now.
