### ISSUE TITLE
Godep - fatal: reference is not a tree: afc9ce26eb6cd43caad9c86a3c4a56ae2a9f39d2

### ISSUE THREAD

**Issue by nguyendangminh** [convox/cli#59]
Hi,
I met the following issue when running "godep restore":

$ $GOPATH/bin/godep restore
\# cd /$GOPATH/src/github.com/briandowns/spinner; git checkout afc9ce26eb6cd43caad9c86a3c4a56ae2a9f39d2
fatal: reference is not a tree: afc9ce26eb6cd43caad9c86a3c4a56ae2a9f39d2
godep: restore: exit status 128

How do I resolve it?

**Comment by rjocoleman** [comment]
I fixed this here: https://github.com/rjocoleman/cli/commit/024425ec73470cda6632f0d0a93a3077533b2442 but it's in the middle of another PR sorry.

```shell
$ go get -u github.com/briandowns/spinner
$ godep update github.com/briandowns/spinner
$ git status
$ godep restore
```

**Comment by nguyendangminh** [comment]
It works! Thanks @rjocoleman
