### ISSUE TITLE
Some things to document

### ISSUE THREAD

**Issue by jordan-thoms** [convox/cli#61]
Not sure which is the correct repo to discuss documentation, but I had a couple of questions as someone looking to switch over from Heroku when things stabilize:

- Is there a heroku run / docker exec equivalent in the CLI or do I need to ssh into one of the ECS machines and do that there?
- How are containers sized in terms of memory, cpu, requirements etc (I believe ECS's scheduler has parameters for those?) - At the bottom of https://docs.convox.com/ it mentions room for 10 512mb containers, but it's not clear to me what that means exactly - is each container limited to 512mb ram?
- Is the `convox system update` command zero-downtime? If it is, it would be good to document it as that's a major advantage over some other systems like deis :)
- How about logging? Right now we use heroku drains to log to logstash through syslog and it's great, would like to be able to do something similar.

Convox is looking great and excited to start playing with it!

**Comment by nzoschke** [comment]
We are getting a convox docs repo going. That will be the best place to open issues / questions like this. cc @mattmanning
