### ISSUE TITLE
Automatically retry deleting the stack on certain uninstall CloudFormation errors

### ISSUE THREAD

**Issue by nzoschke** [convox/cli#68]
Sometimes we see CF events like:

```
07:39:27 UTC-0700	DELETE_FAILED	Custom::EC2AvailabilityZones	AvailabilityZones	Invalid PhysicalResourceId
Physical ID:us-east-1a,us-east-1c,us-east-1d
```

I don't always understand the root cause, but in many cases a second delete will clear this up.

Uninstall would be a better experience if we automate retrying the stack delete once.

**Comment by gjohnson** [comment]
One scenario we've seen: This happened to me after naively deleting resources behind CF's back, and then trying to delete the CF stack.

**Comment by ddollar** [comment]
This should be fixed with the new `DependsOn`
