### ISSUE TITLE
ERROR: AlreadyExistsException: Stack [convox] already exists

### ISSUE THREAD

**Issue by mhuggins** [convox/cli#69]
Hello,

I just installed the convox CLI to give it a shot, and I created a new IAM user for the convox installation.  I assigned it the PowerUserAccess policy thinking that would be enough, but the install crashed due to not having necessary access rights.

I then bumped the IAM user permissions with the AdministratorAccess policy and attempted to rerun, but now I always get an error:

```
Installing Convox...
ERROR: AlreadyExistsException: Stack [convox] already exists
	status code: 400, request id: [473e8316-3e21-11e5-81db-a9ff5ede147c]
```

What do I need to do to revert the initial installation attempt and start over?

**Comment by rjocoleman** [comment]
There should be a cloudformation stack called `convox`, you can delete this to destroy any created resources: https://console.aws.amazon.com/cloudformation/home?region=us-east-1

**Comment by mhuggins** [comment]
Great, that did the trick.  Thank you! :)

**Comment by paulkernfeld** [comment]
Late to the party here, but it would be nice if this problem were explained in a more prominent location. I got a similar issue because I had set up my subnet CIDRs wrong.
