### ISSUE TITLE
Make STACK_NAME, DEVELOPMENT, VERSION as options of "convox install"

### ISSUE THREAD

**Issue by nguyendangminh** [convox/cli#71]
Hi,

As in the source code, we have some more options for "convox install" such as stack name, version,... But they must be set as environment variables:
$ export STACK_NAME=convox2
$ convox install

For more consistency, should we make them as options of the command "convox install"?
$ convox install --stack_name=convox2

**Comment by nzoschke** [comment]
Big +1

These aren't options that most people need to tune but having them undiscoverable doesn't help anyone.

I think `--stack-name` would be the more unix-y CLI format.

**Comment by nguyendangminh** [comment]
I've just submitted a PR https://github.com/convox/cli/pull/78. Please review it.
