### ISSUE TITLE
API Requests seem slow

### ISSUE THREAD

**Issue by jordan-thoms** [convox/cli#73]
```
$ time convox env
RACK_ENV=production

real	0m21.796s
user	0m0.008s
sys	0m0.006s
```

I'm getting pretty slow responses to the API requests I do, and `convox logs` often fails or works for a while and then silently dies.

Is there a verbose mode I can turn on to get more useful information on what is happening here? If it's relevant, I'm running just a single t2.small instance for testing at this stage.

**Comment by ddollar** [comment]
We have tightened up most of these calls. Please let us know if you're still seeing this.
