### ISSUE TITLE
Support convox install via temporary security credentials

### ISSUE THREAD

**Issue by jbuck** [convox/cli#86]
I sign-in to the various AWS accounts I manage by assuming roles within them. To use these temporary credentials you need to pull in a session token in addition to the access key id and secret access key.

I honestly know very little about go, but I think the fix would be pulling in the token: `token := os.Getenv("AWS_SESSION_TOKEN")` and then sending it as the 3rd parameter to CloudFormation credentials: `Credentials: credentials.NewStaticCredentials(access, secret, token),`

Would you like a PR with this fix?

**Comment by ddollar** [comment]
Sorry for not seeing this sooner. We would absolutely accept that PR :)
