### ISSUE TITLE
Change `convox system` command to `convox rack`

### ISSUE THREAD

**Issue by mattmanning** [convox/cli#95]
We need to unify terminology on "rack" so that the documentation and commands will be easier to understand.

**Comment by mattmanning** [comment]
It would be nice to keep system around as an alias with a deprecation warning for a few releases.

**Comment by csquared** [comment]
will take a look at this now

**Comment by mattmanning** [comment]
Fixed by https://github.com/convox/cli/pull/102. Thanks @csquared
